# Generated by Django 5.0.14 on 2025-05-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionContent',
            new_name='Content',
        ),
    ]
