# Generated by Django 5.0.14 on 2025-05-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
